# !/usr/bin/python
# -*- coding: utf-8 -*-

ERR_SUCCESS = [0, u'完成']
ERR_USER_NOT_LOGIN = [40004, u'用户未登录，请重新登录！']
ERR_USER_AUTH = [40005, u'用户权限不够']
ERR_REQUESTWAY = [40006, u'请求方式错误']
# ERR_USER_NOTLOGGED = [8, '用户未登录']
# ERR_USER_AUTH = [14, '用户权限不够']
# ERR_REQUESTWAY = [2, '请求方式错误']
ERR_IMAGE_CAPTCHA = [40013, '验证码错误']
ERR_PWD_ERROR = [40005, '密码错误']
ERR_USER_NOT_EXIST = [40006, '用户不存在']
ERR_ACCOUNT_EXIST = [7, '帐号已存在']
ERR_STAFFNO_EXIST = [15, '员工工号已存在']
ERR_OLDPWD = [4, '旧密码错误']
ERR_ACCOUNT_NOT_MODIFY = [16, '帐号不能修改']
ERR_SMS_CAPTCHA = [20, '短信验证码错误']
ERR_NOT_PHONE = [21, '司机手机号不存在系统中']
ERR_CUSTOMER_EXIST = [22, '公司名称已存在']
ERR_ORDERS_DRIVER_ASSIGNED = [23, '"%s"司机已分配']
ERR_ORDERS_DRIVER_CAR = [24, '"%s"车辆已分配']
ERR_ORDERS_MORE = [25, '分配车辆大于接单车辆数']
ERR_CHECK_BTIME_REPEAT = [26, u'%s上班时间已提交']
ERR_CHECK_ETIME_REPEAT = [27, u'%s下班时间已提交']
ERR_CHECK_DATE_INCONSISTENT = [28, u'签到日期和计划出车日期不一致']
ERR_CUSTOMER_ORDERS_EXISTS = [29, u'接单企业已存在']
